import Head from 'next/head'
import {
  Container,
  Box,
  Heading,
  Stack,
  HStack,
  FormControl,
  FormLabel,
  Input,
  Link,
  Button,
} from '@chakra-ui/react'
import { Inter } from 'next/font/google'
import { useForm } from 'react-hook-form'
import { useState } from 'react'
import type { Data } from './api/hello'
import nl2br from 'react-nl2br'

const inter = Inter({ subsets: ['latin'] })

interface FormProps {
  email: string
}
export default function Home() {
  const { register, handleSubmit } = useForm<FormProps>()
  const [result, setResult] = useState('Email を入力して Submit してください')
  const [loading, setLoading] = useState(false)

  const handleFormSubmit = async (data: FormProps) => {
    setLoading(true)

    const ret = await fetch('/api/hello', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        request: data.email,
      }),
    })

    setLoading(false)
    if (!ret.ok) {
      setResult('Error')
      return
    }

    const apiRes = (await ret.json()) as Data
    setResult(apiRes.result)
  }

  return (
    <>
      <Head>
        <title>Nickname GPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        maxW="container.xl"
        display="grid"
        gridTemplateRows="auto 1fr auto"
        h="100vh"
      >
        <Heading p="2">Nickname GPT</Heading>

        <Box h="full" p="2">
          <Stack>
            <form onSubmit={handleSubmit(handleFormSubmit)}>
              <FormControl id="email">
                <FormLabel>Email:</FormLabel>
                <HStack>
                  <Input {...register('email')} autoFocus />
                  <Button type="submit" colorScheme="blue" isLoading={loading}>
                    Submit
                  </Button>
                </HStack>
              </FormControl>
            </form>

            <Box>{loading ? 'Loading...' : nl2br(result)}</Box>
          </Stack>
        </Box>

        <Box textAlign="center" p="2">
          <Box>
            Copyright &copy;{' '}
            <Link href="https://twitter.com/techtalkjp" color="blue.500">
              coji
            </Link>{' '}
          </Box>
          <Box>
            <Link href="https://github.com/coji/nickname-gpt" color="blue.500">
              GitHub
            </Link>
          </Box>
        </Box>
      </Container>
    </>
  )
}
